---
Name: CTGP-Cafe
WUAPPSVersion: "3.0"
SourcesBaseDir: "."
ModulesBaseDir: "."
Variables:
  PATCHES_DIR: "./modules"
  SOURCES_DIR: "../source"
  INCLUDE_DIR: "../include"
IncludeDirs:
  - "../include"
  - "../include/sead"
  - "../source"
Modules:
  - "$PATCHES_DIR/lib_dynamic_libs"
  - "$PATCHES_DIR/init"
  - "$PATCHES_DIR/patch_MessageRedirection"
  - "$PATCHES_DIR/patch_CourseRedirection"
  - "$PATCHES_DIR/patch_ResourceRedirection"
BuildOptions:
  - "--implicit_typename"
  - "--diag_suppress 1931,1974,1822"
  - "--diag_suppress 381"
  - "-DEPPC"
MinAlign:
  .text: 0x20
  .rodata: 0x100
  .data: 0x20
  .bss: 0x100
Targets:
  Turbo: ~
